services:
  _defaults:
    autowire: true
    autoconfigure: true

  PrototypeIntegration\Demo\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\View\ViewFactoryInterface:
    class: 'PrototypeIntegration\PrototypeIntegration\View\ViewFactory'
    arguments:
      $defaultViewFactory: '@TYPO3\CMS\Fluid\View\FluidViewFactory'

  PrototypeIntegration\Demo\Processors\ContentElements\Ce01Text:
    public: true
  PrototypeIntegration\Demo\Processors\ContentElements\Ce03TextImage:
    public: true
